name: "MAIN DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::600627337186:role/github-actions-thadeu"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "thadeubatista-terraform"
      aws-lock-dynamodb-table: "thadeubatista-terraform-lock"